### ISSUE TITLE
Universeller Hintergrundbeleuchtungsanschluss

### ISSUE THREAD

**Issue by Varbin** [NetLamp/NetLamp#5]
# Fortschritt
- [x] Elektronischer Entwurf 1
- [x] Elektronischer Entwurf 2
- [x] Standart

**Comment by oscilloscopefrog** [comment]
Hi!

**Comment by Varbin** [comment]
Und? Wie sieht es nun mit dem Anschluss aus?

**Comment by oscilloscopefrog** [comment]
muss ich noch mache...die fräsmaschine ist heute ausgefallen..also werde ich gleich ein schönes Bild malen mit dem stecker und den anschlüssen. Meinst du wir könne -12v zum panel weglassen?

**Comment by oscilloscopefrog** [comment]
wenn wir 24v haben in denen schon pwm und enable steckt?

**Comment by Varbin** [comment]
Ja, absolut. Du darfst dich übrigens der Großschreibung bedienen.

**Comment by Varbin** [comment]
@oscilloscopefrog Bitte ein elektronisches Bild verwenden.

**Comment by oscilloscopefrog** [comment]
Also weglassen?

**Comment by Varbin** [comment]
Ja. -12 weglassen.

**Comment by oscilloscopefrog** [comment]
Gut, dann mach ich das gleich. Hast du D-Sub9 Stecker bei dir, egal ob m/w?

**Comment by Varbin** [comment]
Nein.

**Comment by oscilloscopefrog** [comment]
gut, dann bring ich dir welche mit

**Comment by oscilloscopefrog** [comment]
![Uploading D-Sub9_Stecker_NetLamp_Standard.png…]()

**Comment by oscilloscopefrog** [comment]
![Uploading D-Sub9_Stecker_NetLamp_Standard.png…]()

**Comment by oscilloscopefrog** [comment]
wie lade ich ein foto hoch? und vorallen wohin?

**Comment by Varbin** [comment]
Du kannst Dateien anhängen (nur PC).
[Test.txt](https://github.com/NetLamp/NetLamp/files/103539/Test.txt)

**Comment by oscilloscopefrog** [comment]
das hab ich grad versucht

**Comment by oscilloscopefrog** [comment]
dann steht da: "Something went really wrogn, and we cant process that file.

**Comment by Varbin** [comment]
Nimm ne JPG.

**Comment by Varbin** [comment]
![dsub_9pin_plug_cmyk](https://cloud.githubusercontent.com/assets/5983372/12557968/97283618-c38d-11e5-9f1a-656fc66bb78c.jpg)

**Comment by Varbin** [comment]
Das sind die Stecker?

**Comment by oscilloscopefrog** [comment]
warte

**Comment by oscilloscopefrog** [comment]
"Something went really wrong, and we can’t process that file. "

**Comment by oscilloscopefrog** [comment]
![Uploading D-Sub9_Stecker_NetLamp_Standard.jpg…]()

**Comment by Varbin** [comment]
NoScript?

**Comment by oscilloscopefrog** [comment]
![d-sub9_stecker_netlamp_standard](https://cloud.githubusercontent.com/assets/16880961/12558052/f9ed829e-c38d-11e5-952b-1fb4426ebe32.jpg)

**Comment by oscilloscopefrog** [comment]
YEAH!

**Comment by Varbin** [comment]
Danke!
P.S.: Pack bitte den Text in das Textfeld!

**Comment by oscilloscopefrog** [comment]
?

**Comment by oscilloscopefrog** [comment]
der text gehört zur grafik...damit die fürimmer vereint sind

**Comment by Varbin** [comment]
Nein. Bitte nicht.

**Comment by Varbin** [comment]
Ich lösche mal grade die "Fehluploads".

**Comment by oscilloscopefrog** [comment]
aber das bild nicht!

**Comment by Varbin** [comment]
# Fortschritt:
- Phase 1.

**Comment by Varbin** [comment]
Ach, und es gilt #14

**Comment by oscilloscopefrog** [comment]
Ist das hier eig. öffentlich?!

**Comment by Varbin** [comment]
Ja.

**Comment by oscilloscopefrog** [comment]
wie kann ich diese [..] email-Benachrichtigung abstellen die ich jedesmal kriege wenn du was schreibst

**Comment by Varbin** [comment]
Rechts -> Unsubscribe

**Comment by oscilloscopefrog** [comment]
Wie lang darf denn so eine Leitung sein? Ich habe jetzt gerade einen Stecker angelötet und an dem aderem Ende wollte ich ein Stück Holz mit Lusterklemmen befestingen. Sind 2m gut? Ich finde schon. Das war jetzt erstmal mein Kabel, da ich immoment keien D-Sub 9 Steckergehäuse habe. Wenn ich noch welche finde/besorge mach ich dir auch so ein Kabel mit einem Holzblock am anderen ande mit Lusterklemmen und Beschriftung. Nur zur erinnerung, das ist die Leitung von der Steuereinheit (Arduino/Pi) zum panel, wo dann die Schnittstelle ist.

**Comment by Varbin** [comment]
Naja, das dürfen schon ein paar Meter seien, die Frequenz ist ja nicht so hoch.

**Comment by Varbin** [comment]
Gibt es eigentlich kleinere Sub-D?

So was wie das:
![5-Poliger Sub-D-Stecker](https://cloud.githubusercontent.com/assets/5983372/12561174/ee06083c-c39e-11e5-8084-dafe65964667.jpg)

**Comment by Varbin** [comment]
Das Team lehnt dies ab.

**Comment by Varbin** [comment]
Wie sieht es damit aus:

[~~Spezifikation.pdf~~](https://github.com/NetLamp/NetLamp/files/103753/Spezifikation.pdf)
[~~Spezifikation.docx~~](https://github.com/NetLamp/NetLamp/files/103754/Spezifikation.docx)

**Comment by Varbin** [comment]
Update:
[~~Spezifikation.pdf~~](https://github.com/NetLamp/NetLamp/files/103769/Spezifikation.pdf)
[~~Spezifikation.pdf~~](https://github.com/NetLamp/NetLamp/files/103809/Spezifikation.pdf)
[Spezifikation.pdf](https://github.com/NetLamp/NetLamp/files/103811/Spezifikation.pdf)

**Comment by Varbin** [comment]
Das Team stimmt den Entwürfen zu.

**Comment by Varbin** [comment]
# Fortschrit
- Phase 2

**Comment by oscilloscopefrog** [comment]
Jetzt haben wir einen Stecker an dem Ende was zum Panel geht, was ist mit dem anderen Ende? Soll dort auch ein D-Sub 9 Stecker angebracht werden oder soll einfach das kabel mithilfe eine Kabelverschraubung in ein Gehäuse gehen und dort fest verlötet werden/mit Klemmen für die Lochrasterplatine/PCB versehen werden?

**Comment by Varbin** [comment]
Ja. Gleiches Pinout.

**Comment by Varbin** [comment]
Bzw. dem entsprechendes Pinout.

**Comment by Varbin** [comment]
[Spezifikation.pdf](https://github.com/NetLamp/NetLamp/files/103818/Spezifikation.pdf)

**Comment by oscilloscopefrog** [comment]
Aber das PCB Soll doch sicher in ein Gehäuse (wenn möglich mit einsehbahrem Deckel) und die D-Sub 9 Stecker sollen dan im Gehäuse verbaut werden, oder?

**Comment by Varbin** [comment]
Nein. Außerhalb, das zum anstecken.

**Comment by oscilloscopefrog** [comment]
(in der Gehäusewand)

**Comment by Varbin** [comment]
Ja.

**Comment by oscilloscopefrog** [comment]
(Sodass die Lötseite innen ist und die Anschlussseite ausßen)

**Comment by Varbin** [comment]
@oscilloscopefrog 
[Spezifikation.pdf](https://github.com/NetLamp/NetLamp/files/103819/Spezifikation.pdf)

Auf ein letztes (hoffentlich).

**Comment by Varbin** [comment]
@oscilloscopefrog Ja

**Comment by oscilloscopefrog** [comment]
Warum kann ich mich nicht Unsubcriben?

**Comment by oscilloscopefrog** [comment]
der subscribed mich automatisch

**Comment by Varbin** [comment]
Dann stimm dem Entwurf zu und schließ das Issue.

**Comment by oscilloscopefrog** [comment]
Ich stimme zu

**Comment by Varbin** [comment]
Erweiterung: Erkennung der Lampen.

**Comment by Varbin** [comment]
Verlagerung in ein anderes Problem.
